#!/usr/bin/env bash
#
# Copyright © 2025 Qin Fandong
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# *** UPDATE THESE WITH EACH BUILD ***
# {
PKGNAM='systemd'
VERSION='257.8'
ARCH="${ARCH:-x86_64}"
BUILD="${BUILD:-1}"
SRCTYPE='tar.gz'
# }

# Set initial variables
CWD=$(dirname $(readlink -f "$0"))
SOURCE="${PKGNAM}-${VERSION}.${SRCTYPE}"
PKGTYPE="${PKGTYPE:-txz}"
TMP="${TMP:-/tmp}"
PKG="${TMP}/package-${PKGNAM}-${VERSION}-${ARCH}"
MAKEFLAGS="-j$(nproc)"

cd "$CWD"

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [[ -n "$PRINT_PACKAGE_NAME" ]]
then
  echo "$SOURCE"
  exit 0
fi

# location to build the source
if [[ ! -d "$TMP" ]]
then
  mkdir -p "$TMP"
fi

if [[ -d "$PKG" ]]
then
  rm -rf "$PKG"
fi

mkdir -p "$PKG"

# Prepare
{
  if [[ -d "./${PKGNAM}-${VERSION}" ]]
  then
    rm -rf "./${PKGNAM}-${VERSION}" 
  fi

  tar -xf "$SOURCE"
  cd "./${PKGNAM}-${VERSION}"

  sed -i -e 's/GROUP="render"/GROUP="video"/' \
         -e 's/GROUP="sgx", //' ./rules.d/50-udev-default.rules.in
}

# Build
{
  mkdir -p ./build/
  cd ./build/
  meson setup ..                \
        --prefix=/usr           \
        --buildtype=release     \
        -D default-dnssec=no    \
        -D firstboot=false      \
        -D install-tests=false  \
        -D ldconfig=false       \
        -D sysusers=false       \
        -D rpmmacrosdir=no      \
        -D homed=disabled       \
        -D userdb=false         \
        -D man=disabled         \
        -D mode=release         \
        -D pamconfdir=no        \
        -D dev-kvm-mode=0660    \
        -D nobody-group=nogroup \
        -D sysupdate=disabled   \
        -D ukify=disabled       \
        -D docdir="/usr/share/doc/${PKGNAM}-${VERSION}"
  ninja
}

# Check
{
  REL_NOT_FOUND=0
  NAME_NOT_FOUND=0
  CHECK_OK=1

  if [[ ! -e /etc/os-release ]]
  then
    REL_NOT_FOUND=1
    echo 'NAME="Linux From Scratch"' >/etc/os-release
  fi

  source /etc/os-release

  if [[ -z "$NAME" ]]
  then
    NAME_NOT_FOUND=1
    echo 'NAME="Linux From Scratch"' >>/etc/os-release
  fi

  if ! ninja test
  then
    CHECK_OK=0
  fi

  if [[ 1 -eq "$REL_NOT_FOUND" ]]
  then
    rm -f /etc/os-release
  fi

  if [[ 1 -eq "$NAME_NOT_FOUND" ]]
  then
    sed -i '/^NAME="Linux From Scratch"/d' /etc/os-release
  fi

  if [[ 0 -eq "$CHECK_OK" ]]
  then
    # Ignore check errors, systemd:core / test-namespace will failed in chroot environment
    :
  fi
}

# Install
{
  DESTDIR="$PKG" ninja install

  tar -xf "${CWD}/${PKGNAM}-man-pages-${VERSION}.tar.xz" \
      --no-same-owner --strip-components=1 \
      -C "${PKG}/usr/share/man/"
}

# Make packages
{
  mkdir -p "${PKG}/usr/doc/${PKGNAM}-${VERSION}/"
  mkdir -p "${PKG}/install/"

  install -Dm 0755 "${CWD}/${PKGNAM}.SlackBuild" \
                   "${PKG}/usr/doc/${PKGNAM}-${VERSION}/${PKGNAM}.SlackBuild"
  install -Dm 0644 "${CWD}/slack-desc" "${PKG}/install/slack-desc"
  install -Dm 0755 "${CWD}/doinst.sh" "${PKG}/install/doinst.sh"

  cd "$PKG"
  makepkg -l y -c n "${TMP}/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.${PKGTYPE}"
}

# Clean
{
  rm -rf "$PKG"
  rm -rf "${CWD}/${PKGNAM}-${VERSION}"
}
