#!/usr/bin/env bash
#
# Copyright © 2025 Qin Fandong
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# *** UPDATE THESE WITH EACH BUILD ***
# {
PKGNAM='python'
VERSION='3.13.7'
ARCH="${ARCH:-x86_64}"
BUILD="${BUILD:-1}"
SRCTYPE='tar.xz'
  # modules (tar.gz)
  # {
FLIT_CORE_VER='3.12.0'
SETUPTOOLS_VER='80.9.0'
WHEEL_VER='0.46.1'
PACKAGING_VER='25.0'
  # }
# }

# Set initial variables
CWD=$(dirname $(readlink -f "$0"))
SOURCE="${PKGNAM^}-${VERSION}.${SRCTYPE}"
PKGTYPE="${PKGTYPE:-txz}"
TMP="${TMP:-/tmp}"
PKG="${TMP}/package-${PKGNAM}-${VERSION}-${ARCH}"
MAKEFLAGS="-j$(nproc)"

cd "$CWD"

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [[ -n "$PRINT_PACKAGE_NAME" ]]
then
  echo "$SOURCE"
  exit 0
fi

# location to build the source
if [[ ! -d "$TMP" ]]
then
  mkdir -p "$TMP"
fi

if [[ -d "$PKG" ]]
then
  rm -rf "$PKG"
fi

mkdir -p "$PKG"

# Prepare
{
  if [[ -d "./${PKGNAM^}-${VERSION}" ]]
  then
    rm -rf "./${PKGNAM^}-${VERSION}"
  fi

  tar -xf "$SOURCE"
  cd "./${PKGNAM^}-${VERSION}"
}

# Build
{
  ./configure --prefix=/usr        \
              --enable-shared      \
              --with-system-expat  \
              --enable-optimizations
  make
}

# Check
{
  if ! make test TESTOPTS="--timeout 300"
  then
    if which curl >/dev/null && \
      [[ '200' -eq \
          $(curl -o /dev/null -sw '%{http_code}' 'www.pythontest.net') ]]
    then
      # Ignore errors, no network connection
      :
    else
      # Ignore errors, test_ssl will failed in chroot environment
      :
    fi
  fi
  :
}

# Install
{
  make DESTDIR="$PKG" install

  cat >"${PKG}/etc/pip.conf" << EOF
[global]
root-user-action = ignore
disable-pip-version-check = true
EOF

  # Install documents
  install -dm 0755 "${PKG}/usr/share/doc/${PKGNAM}-${VERSION}/html/"
  tar --strip-components=1  \
      --no-same-owner       \
      --no-same-permissions \
      -C "${PKG}/usr/share/doc/${PKGNAM}-${VERSION}/html" \
      -xvf "../${PKGNAM}-${VERSION}-docs-html.tar.bz2"

  #
  # Install extra modules
  #
  # flit_core
  {
    cd "$CWD"
    tar -xf "./flit_core-${FLIT_CORE_VER}.tar.gz"
    cd "./flit_core-${FLIT_CORE_VER}/"
    pip3 -v wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$PWD"
    pip3 -v install --root "$PKG" --no-index --find-links dist flit_core
    cd "$CWD"
    rm -rf "./flit_core-${FLIT_CORE_VER}/"
  }
  # packaging
  {
    cd "$CWD"
    tar -xf "./packaging-${PACKAGING_VER}.tar.gz"
    cd "./packaging-${PACKAGING_VER}/"
    # Requires flit_core
    export PYTHONPATH="${PKG}/usr/lib/${PKGNAM}${VERSION%.*}/site-packages/"
    pip3 -v wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$PWD"
    pip3 -v install --root "$PKG" --no-index --find-links dist packaging
    unset PYTHONPATH
    cd "$CWD"
    rm -rf "./packaging-${PACKAGING_VER}/"
  }
  # wheel
  {
    cd "$CWD"
    tar -xf "./wheel-${WHEEL_VER}.tar.gz"
    cd "./wheel-${WHEEL_VER}/"
    # Requires flit_core
    export PYTHONPATH="${PKG}/usr/lib/${PKGNAM}${VERSION%.*}/site-packages/"
    pip3 -v wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$PWD"
    pip3 -v install --root "$PKG" --no-index --find-links dist wheel
    unset PYTHONPATH
    cd "$CWD"
    rm -rf "./wheel-${WHEEL_VER}/"
  }
  # setuptools
  {
    cd "$CWD"
    tar -xf "./setuptools-${SETUPTOOLS_VER}.tar.gz"
    cd "./setuptools-${SETUPTOOLS_VER}/"
    pip3 -v wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$PWD"
    pip3 -v install --root "$PKG" --no-index --find-links dist setuptools
    cd "$CWD"
    rm -rf "./setuptools-${SETUPTOOLS_VER}/"
  }
}

# Make packages
{
  mkdir -p "${PKG}/usr/doc/${PKGNAM}-${VERSION}/"
  mkdir -p "${PKG}/install/"

  install -Dm 0755 "${CWD}/${PKGNAM}.SlackBuild" \
                   "${PKG}/usr/doc/${PKGNAM}-${VERSION}/${PKGNAM}.SlackBuild"
  install -Dm 0644 "${CWD}/slack-desc" "${PKG}/install/slack-desc"
  install -Dm 0755 "${CWD}/doinst.sh" "${PKG}/install/doinst.sh"

  cd "$PKG"
  makepkg -l y -c n "${TMP}/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.${PKGTYPE}"
}

# Clean
{
  rm -rf "$PKG"
  rm -rf "${CWD}/${PKGNAM^}-${VERSION}"
  rmdir "${CWD}/dist/"
}
